### PR TITLE
Changed human readable device name and added RSSI and SNR + default behavior changes

### PR DESCRIPTION
**Pull request by noon92**
Added SNR and RSSI. Ideally, I'd like to have them only populate when hops_away > 0, but that's beyond my skills. @ianmcorvidae ?

Also, changed the human readable device name from "Meshtastic NODEID" to the node's long-name. Big quality of life improvement.

### CODE REVIEW

**Comment by noon92** [comment]
Changed default temperature unit to Celsius and added --fahrenheit argument.
Changed default included channels to wildcard (include all channels).

**Comment by ianmcorvidae** [comment]
Sorry to take so long to get to this. It looks like you accidentally ate the RSSI/SNR additions when adding the fahrenheit option: https://github.com/pdxlocations/meshtastic-ha-entity-builder/pull/13/commits/0b28e3fd3f555974dfdd803a35ff87a5c22a28e8

other than that, I think this looks good, though I suppose I might change the help text to be slightly more neutral, haha

**Comment by ianmcorvidae** [comment]
For RSSI/SNR and hops_away, both are per-packet (so two subsequent packets could have hops_away of 0 and then higher than 0), but you could probably make it so the value only updates when hops_away is 0, perhaps something like:

```
    value_template: >-
      {{% if value_json.from == {node_num} and value_json.snr is defined and (value_json.hops_away is not defined or value_json.hops_away == 0) %}}
          {{{{ value_json.snr}}}}
      {{% else %}}
          {{{{ this.state }}}}
      {{% endif %}}
```

(I haven't tested that so I don't know for sure if I have it totally right. I think hops_away might just never appear in the JSON when it's 0, which might mean only the `is not defined` check is necessary)

**Comment by noon92** [comment]
> For RSSI/SNR and hops_away, both are per-packet (so two subsequent packets could have hops_away of 0 and then higher than 0), but you could probably make it so the value only updates when hops_away is 0, perhaps something like:

Can you do this? I don't have the headspace atm

**Comment by noon92** [comment]
Added SNR and RSSI back in. Leaving the "biased" help text! You can take it out if you like 😅

**Comment by ianmcorvidae** [comment]
I'll go ahead and merge this and then update the text. I don't think the text is really biased or wrong per se, just kind of irrelevant to the help for a command-line script, haha

**Pull request merged**
